### ISSUE TITLE
Issue in line 6, line 1 and line 22

### ISSUE THREAD

**Issue by JsonProgramer** [instagrambot/instabot#478]
Traceback (most recent call last):
  File "example.py", line 6, in <module>
    from src import InstaBot
  File "/root/instabot.py/src/__init__.py", line 1, in <module>
    from .instabot import InstaBot
  File "/root/instabot.py/src/instabot.py", line 22, in <module>
    from fake_useragent import UserAgent
ImportError: No module named fake_useragent

I'm running it on Kali Linux. Any ideas why it isn't working?

**Comment by sudoguy** [comment]
Wrong repo
